=== dvaneynde/hwdriver/DomoticConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dlvmechanografie.eu/DomoticConfig" xmlns:tns="http://dlvmechanografie.eu/DomoticConfig"
	elementFormDefault="qualified">
	<element name="domotic">
		<complexType>
			<choice maxOccurs="unbounded">

				<!-- sensors -->
				<element name="switch" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:BlockWithChannelStruct">
								<attribute name="singleClick" type="boolean" default="true" />
								<attribute name="longClick" type="boolean" default="false" />
								<attribute name="doubleClick" type="boolean" default="false" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="dimmerSwitches" type="tns:BlockWithChannelUpDownStruct" minOccurs="0" maxOccurs="1" />
				<element name="timer" type="tns:timerType" />
				<element name="timerDayNight" type="tns:timerType" />
				<element name="repeatOff" type="tns:repeatOffType" />
				<element name="windSensor" type="tns:windSensorType" />
				<element name="lightGauge" type="tns:lightGaugeType" />

				<!-- actuators -->
				<element name="lamp" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:OnOffToggleActuatorStruct">
								<attribute name="autoOffSec" type="int" use="optional" />
								<attribute name="blink" type="boolean" use="optional" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="fan" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:OnOffToggleActuatorStruct">
								<attribute name="onSec" type="int" use="optional" />
								<attribute name="delayOnSec" type="int" use="optional" />
								<attribute name="delayOffSec" type="int" use="optional" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="dimmedLamp" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:BlockWithChannelStruct">
								<sequence>
									<choice maxOccurs="unbounded">
										<element name="on">
											<complexType>
												<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
											</complexType>
										</element>
										<element name="off">
											<complexType>
												<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
											</complexType>
										</element>
										<element name="toggle">
											<complexType>
												<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
											</complexType>
										</element>
										<element name="dimmerSwitches">
											<complexType>
												<attribute name="src" type="IDREF" use="required" />
											</complexType>
										</element>
									</choice>
								</sequence>
								<attribute name="fullOnHwOutput" type="int" use="required" />
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="screen" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:BlockWithChannelUpDownStruct">
								<sequence>
									<element name="upDown" maxOccurs="3">
										<complexType>
											<attribute name="srcUp" type="IDREF" use="required" />
											<attribute name="srcDown" type="IDREF" use="required" />
											<attribute name="event" type="string" use="optional" default="SingleClick" />
										</complexType>
									</element>
								</sequence>
								<attribute name="motor-up-time" type="int" />
								<attribute name="motor-dn-time" type="int" />
							</extension>
						</complexContent>
					</complexType>
				</element>

				<!-- controllers -->
				<element name="newyear" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:OnOffToggleActuatorStruct">
								<attribute name="start" type="dateTime"></attribute>
								<attribute name="end" type="dateTime"></attribute>
							</extension>
						</complexContent>
					</complexType>
				</element>
				<element name="sunWindController" type="tns:SunWindControllerStruct" />
				<element name="antiBurglar" minOccurs="0" maxOccurs="1">
					<complexType>
						<complexContent>
							<extension base="tns:OnOffToggleActuatorStruct">
								<sequence>
									<element name="sun" minOccurs="0">
										<complexType>
											<attribute name="sensor" type="IDREF" use="required" />
										</complexType>
									</element>
								</sequence>
								<attribute name="start" type="string" />
								<attribute name="end" type="string" />
							</extension>
						</complexContent>
					</complexType>

				</element>
			</choice>
		</complexType>
	</element>

	<complexType name="SunWindControllerStruct">
		<complexContent>
			<extension base="tns:BlockWithChannelStruct">
				<sequence>
					<element name="wind" minOccurs="0">
						<complexType>
							<attribute name="sensor" type="IDREF" use="required" />
						</complexType>
					</element>
					<element name="sun" minOccurs="0">
						<complexType>
							<attribute name="sensor" type="IDREF" use="required" />
						</complexType>
					</element>
					<element name="screen" maxOccurs="unbounded">
						<complexType>
							<attribute name="name" type="IDREF" use="required" />
						</complexType>
					</element>
				</sequence>
				<attribute name="azimuthStart" type="double" use="optional"/>
				<attribute name="azimuthEnd" type="double" use="optional"/>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="switchEventType">
		<restriction base="string">
			<enumeration value="single" />
			<enumeration value="double" />
			<enumeration value="long" />
		</restriction>
	</simpleType>
	<complexType name="timerType">
		<complexContent>
			<extension base="tns:BlockStruct">
				<sequence>
					<element name="on">
						<complexType>
							<attribute name="hour" type="int" use="required" />
							<attribute name="minute" type="int" use="required" />
						</complexType>
					</element>
					<element name="off">
						<complexType>
							<attribute name="hour" type="int" use="required" />
							<attribute name="minute" type="int" use="required" />
						</complexType>
					</element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="repeatOffType">
		<complexContent>
			<extension base="tns:timerType">
				<attribute name="intervalSec" use="required" type="int" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="windSensorType">
		<complexContent>
			<extension base="tns:BlockWithChannelStruct">
				<attribute name="highFreq" use="required" />
				<attribute name="lowFreq" use="required" />
				<!-- <attribute name="highTimeBeforeAlert" use="required" /> -->
				<attribute name="lowTimeToResetAlert" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="lightGaugeType">
		<complexContent>
			<extension base="tns:BlockWithChannelStruct">
				<attribute name="threshold" use="required" />
				<attribute name="low2highTime" use="required" />
				<attribute name="high2lowTime" use="required" />
			</extension>
		</complexContent>
	</complexType>

	<complexType name="AllSwitchStruct">
		<attribute name="switch" use="required" type="IDREF" />
		<attribute name="allOff" default="true" type="boolean" />
		<attribute name="allOn" default="false" type="boolean" />
	</complexType>
	<complexType name="BlockStruct">
		<attribute name="name" use="required" type="ID" />
		<attribute name="desc" use="optional" type="string" />
		<attribute name="ui" type="string" use="optional" />
	</complexType>
	<complexType name="BlockWithChannelStruct">
		<complexContent>
			<extension base="tns:BlockStruct">
				<annotation>
					<documentation>Default channel naam is name attribute, kan
						overridden door
						channel attribuut.
					</documentation>
				</annotation>
				<attribute name="channel" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>

	<attributeGroup name="EventConsumerAttributeGroup">
		<attribute name="src" type="IDREF" use="required" />
		<attribute name="event" type="string" use="optional" default="SingleClick" />
	</attributeGroup>

	<complexType name="OnOffToggleActuatorStruct">
		<complexContent>
			<extension base="tns:BlockWithChannelStruct">
				<sequence>
					<choice maxOccurs="unbounded">
						<element name="on">
							<complexType>
								<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
							</complexType>
						</element>
						<element name="off">
							<complexType>
								<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
							</complexType>
						</element>
						<element name="toggle">
							<complexType>
								<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
							</complexType>
						</element>
						<element name="ecoToggle">
							<complexType>
								<attributeGroup ref="tns:EventConsumerAttributeGroup"></attributeGroup>
							</complexType>
						</element>
						<element name="delayedOnOff">
							<complexType>
								<attribute name="src" type="IDREF" use="required" />
							</complexType>
						</element>
					</choice>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="BlockWithChannelUpDownStruct">
		<complexContent>
			<extension base="tns:BlockStruct">
				<annotation>
					<documentation>Default channel naam is name attribute, kan
						overridden door
						channel attribuut.
					</documentation>
				</annotation>
				<attribute name="channelDown" type="string" use="optional" />
				<attribute name="channelUp" type="string" use="optional" />
			</extension>
		</complexContent>
	</complexType>

</schema>

=== dvaneynde/hwdriver/domotic/src/test/resources/TestDomoticConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<domotic xmlns="http://dlvmechanografie.eu/DomoticConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DomoticConfig ../../../DomoticConfig.xsd ">

	<switch channel="5" name="SchakAllOnOff" desc="Alle lichten aan/uit." />

	<repeatOff name="GarageAutoUit" desc="test repeat off"
		intervalSec="60">
		<on hour="21" minute="0" />
		<off hour="21" minute="15" />
	</repeatOff>

	<switch channel="1" name="SchakLichtBadkamer0" desc="Licht badkamer gelijkvloers." />
	<lamp channel="3" name="LichtBadkamer0">
		<toggle src="SchakLichtBadkamer0" event="SingleClick" />
		<off src="SchakAllOnOff" event="LongClick" />
		<off src="GarageAutoUit" event="Off" />
	</lamp>

	<switch channel="10" name="SchakFanBadkamer0" />
	<fan name="FanBadkamer0" channel="6">
		<toggle src="SchakFanBadkamer0" event="SingleClick" />
		<off src="SchakFanBadkamer0" event="LongClick" />
		<delayedOnOff src="LichtBadkamer0" />
	</fan>

	<switch channel="2" name="SchakLichtWC0" desc="Licht badkamer boven." />
	<lamp channel="4" name="LichtWC0">
		<toggle src="SchakLichtWC0" event="SingleClick" />
		<off src="SchakAllOnOff" event="LongClick" />
	</lamp>

	<switch channel="11" name="SchakFanWC0" />
	<fan name="FanWC0" channel="7" desc="Ventilator WC gelijkvloers.">
		<toggle src="SchakFanWC0" event="SingleClick" />
		<off src="SchakFanWC0" event="LongClick" />
		<delayedOnOff src="LichtWC0" />
	</fan>

	<!-- Dimmers -->
	<dimmerSwitches name="SchakLichtVeranda" />
	<dimmedLamp name="LichtVeranda" fullOnHwOutput="4095" desc="Veranda" ui="Beneden:1">
		<dimmerSwitches src="SchakLichtVeranda"/>
		<off src="SchakAllOnOff" event="LongClick" />
	</dimmedLamp>


	<!-- Screens -->
	<switch name="SchakScreenBreedUp" />
	<switch name="SchakScreenBreedDown" />
	<switch name="SchakScreenLangUp" />
	<switch name="SchakScreenLangDown" />
	<switch name="SchakScreenAllUp" singleClick="true" longClick="true" />
	<switch name="SchakScreenAllDown" singleClick="true" longClick="true" />

	<screen name="ScreenBreed" desc="Breed" motor-up-time="40"
		motor-dn-time="36">
		<upDown srcUp="SchakScreenBreedUp" srcDown="SchakScreenBreedDown" />
		<upDown srcUp="SchakScreenAllUp" srcDown="SchakScreenAllDown"
			event="LongClick" />
	</screen>
	<screen name="ScreenLang" desc="Smal" motor-up-time="100"
		motor-dn-time="100">
		<upDown srcUp="SchakScreenLangUp" srcDown="SchakScreenLangDown" />
		<upDown srcUp="SchakScreenAllUp" srcDown="SchakScreenAllDown"
			event="LongClick" />
	</screen>

	<windSensor name="Windmeter" channel="Windmeter" highFreq="5"
		lowFreq="2" lowTimeToResetAlert="60" />
	<lightGauge name="LichtsensorScreen" channel="AnalogIn"
		threshold="3000" low2highTime="10" high2lowTime="60" />


	<sunWindController name="ZonWindAutomaat" desc="Zon/Wind Automaat"
		ui="Screens:0">
		<!-- TODO zon en wind, afhankelijk van groep andere parameters rond lichtsterkte, 
			ook rekening houdende met zonnestand. Dus hier moeten groepen kunnen gedefinieerd 
			worden, met verschillende parameters, b.v. ook alarm etc. moeten hier bij 
			wind en sun. -->
		<wind sensor="Windmeter" />
		<sun sensor="LichtsensorScreen" />
		<screen name="ScreenBreed" />
		<screen name="ScreenLang" />
	</sunWindController>


	<lightGauge name="LichtsensorNacht" threshold="4000"
		low2highTime="10" high2lowTime="60" channel="AnalogIn" />

	<lamp name="indicator">
		<on src="LichtsensorNacht" event="ALARM" />
		<off src="LichtsensorNacht" event="SAFE" />
	</lamp>

</domotic>
